name: Generate Version and Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore daily run count from cache
      id: cache_daily_run
      uses: actions/cache@v4
      with:
        path: .github/.daily_run_count
        key: ${{ runner.os }}-run-count-${{ github.ref_name }}-${{ env.TODAY_DATE || '' }}

    - name: Generate version string
      id: versioning
      run: |
        mkdir -p .github
        TODAY=$(date +'%Y-%m-%d')
        DATE_CODE=$(date +'%y%m%d')
        COUNT_FILE=".github/.daily_run_count"

        RUN_NUM=0
        if [ -f "$COUNT_FILE" ]; then
          RUN_NUM=$(cat "$COUNT_FILE")
        fi
        RUN_NUM=$((RUN_NUM + 1))
        printf "%s" "$RUN_NUM" > "$COUNT_FILE"

        PADDED_RUN=$(printf "%02d" "$RUN_NUM")
        VERSION="${DATE_CODE}${PADDED_RUN}"

        echo "VERSION_STRING=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION_STRING=$VERSION"
        echo "$TODAY" >> $GITHUB_ENV  # Used for consistent cache key

    - name: Save test_version.txt
      run: echo "${{ steps.versioning.outputs.VERSION_STRING }}" > test_version.txt

    - name: Zip repository
      run: zip -r dab-compliance-suite.zip . -x ".git/*" -x "dab-compliance-suite.zip"

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: dab-compliance-suite
        path: dab-compliance-suite.zip

    - name: Save daily run count to cache
      uses: actions/cache/save@v4
      with:
        path: .github/.daily_run_count
        key: ${{ runner.os }}-run-count-${{ github.ref_name }}-${{ env.TODAY_DATE }}