name: Generate Test Version on Push

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Generate dynamic 8-digit version
        id: version
        run: |
          DATE=$(date +'%y%m%d')
          TODAY=$(date +'%Y-%m-%d')

          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')

          if [ "$LAST_COMMIT_DATE" = "$TODAY" ]; then
            COUNT=$(git log --since=midnight --pretty=oneline | wc -l)
            VERSION="${DATE}$(printf "%02d" $COUNT)"
          else
            VERSION="${DATE}01"
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "✅ Generated version: $VERSION"

      - name: Display generated version
        run: echo "Generated version: ${{ steps.version.outputs.version }}"

      - name: Zip the entire repository
        run: |
          zip -r dab-compliance-suite.zip . -x ".git/*"

      - name: Upload dab-compliance-suite.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dab-compliance-suite
          path: dab-compliance-suite.zip
