name: Generate Test Version on Push

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 8-digit Test Version File (no commit)
        run: |
          DATE=$(date +'%y%m%d')
          VERSION_FILE="test_version.txt"

          if [ -f "$VERSION_FILE" ]; then
            LAST_VERSION=$(cat $VERSION_FILE)
            LAST_DATE=${LAST_VERSION:0:6}
            LAST_COUNT=${LAST_VERSION:6:2}
            if [ "$LAST_DATE" = "$DATE" ]; then
              COUNT=$(printf "%02d" $((10#$LAST_COUNT + 1)))
              VERSION="${DATE}${COUNT}"
            else
              VERSION="${DATE}01"
            fi
          else
            VERSION="${DATE}01"
          fi

          echo "$VERSION" > test_version.txt
          echo "Generated version: $VERSION"

      - name: Upload version file as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test_version
          path: test_version.txt
