name: Generate Version and Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for GitHub CLI API calls

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y curl
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
          sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install -y gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get today's push count on main
      id: push_count
      run: |
        TODAY=$(date +'%Y-%m-%d')
        REPO="${{ github.repository }}"

        COUNT=$(gh api repos/$REPO/commits \
          -f sha=main \
          -f since="${TODAY}T00:00:00Z" \
          -f until="${TODAY}T23:59:59Z" \
          --jq 'length')

        INCREMENTED=$(($COUNT + 1))
        PADDED_COUNT=$(printf "%02d" "$INCREMENTED")

        DATE_CODE=$(date +'%y%m%d')
        VERSION_STRING="${DATE_CODE}${PADDED_COUNT}"

        echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_OUTPUT
        echo "$VERSION_STRING" > test_version.txt

    - name: Zip repository
      run: zip -r dab-compliance-suite.zip . -x ".git/*" -x "dab-compliance-suite.zip"

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: dab-compliance-suite
        path: dab-compliance-suite.zip

    - name: Upload test_version.txt
      uses: actions/upload-artifact@v4
      with:
        name: test-version
        path: test_version.txt