name: Generate Version and Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed for `gh` API access
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get today's push count on main
      id: push_count
      run: |
        TODAY=$(date +'%Y-%m-%d')
        REPO="${{ github.repository }}"

        COUNT=$(gh api repos/$REPO/commits \
          -f sha=main \
          -f since="${TODAY}T00:00:00Z" \
          -f until="${TODAY}T23:59:59Z" \
          --jq 'length')

        INCREMENTED=$(($COUNT + 1))
        PADDED_COUNT=$(printf "%02d" "$INCREMENTED")

        DATE_CODE=$(date +'%y%m%d')
        VERSION_STRING="${DATE_CODE}${PADDED_COUNT}"

        echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_OUTPUT
        echo "VERSION_STRING=$VERSION_STRING"
        echo "$VERSION_STRING" > test_version.txt

    - name: Zip repository
      run: zip -r dab-compliance-suite.zip . -x ".git/*" -x "dab-compliance-suite.zip"

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: dab-compliance-suite
        path: dab-compliance-suite.zip

    - name: Upload test_version.txt
      uses: actions/upload-artifact@v4
      with:
        name: test-version
        path: test_version.txt