name: Generate Test Version on Push

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Full Git History
        run: |
          git fetch --all

      - name: Generate 8-digit Test Version File (no commit)
        run: |
          DATE=$(date +'%y%m%d')
          VERSION_FILE="test_version.txt"

          # Get last committed version from origin/main if it exists
          LAST_VERSION=$(git show origin/main:$VERSION_FILE 2>/dev/null || echo "")
          
          if [ -n "$LAST_VERSION" ]; then
            LAST_DATE=${LAST_VERSION:0:6}
            LAST_COUNT=${LAST_VERSION:6:2}
            if [ "$LAST_DATE" = "$DATE" ]; then
              COUNT=$(printf "%02d" $((10#$LAST_COUNT + 1)))
              VERSION="${DATE}${COUNT}"
            else
              VERSION="${DATE}01"
            fi
          else
            VERSION="${DATE}01"
          fi

          echo "$VERSION" > test_version.txt
          echo "✅ Generated test version: $VERSION"

      - name: Zip entire repository as dab-compliance-suite.zip
        run: |
          zip -r dab-compliance-suite.zip . -x ".git/*"

      - name: Upload dab-compliance-suite.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dab-compliance-suite
          path: dab-compliance-suite.zip
