name: Generate Version and Build Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get today’s push count from git log
      id: version
      run: |
        TODAY=$(date +'%Y-%m-%d')
        DATE_CODE=$(date +'%y%m%d')

        # Fetch full history just in case shallow clone is used
        git fetch --unshallow || true

        # Count commits on main made today
        COUNT=$(git log origin/main --since="$TODAY 00:00" --until="$TODAY 23:59" --pretty=oneline | wc -l)

        # Add 1 to get this run's version index
        NEXT_COUNT=$((COUNT + 1))
        PADDED=$(printf "%02d" "$NEXT_COUNT")

        VERSION_STRING="${DATE_CODE}${PADDED}"
        echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_OUTPUT
        echo "$VERSION_STRING" > test_version.txt

    - name: Zip repository
      run: zip -r dab-compliance-suite.zip . -x ".git/*" -x "dab-compliance-suite.zip"

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: dab-compliance-suite
        path: dab-compliance-suite.zip

    - name: Upload test_version.txt
      uses: actions/upload-artifact@v4
      with:
        name: test-version
        path: test_version.txt
